/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente.justificarrotina;

/**
 *
 * @author rafaeld
 */
public class JustificarRotinaView extends javax.swing.JFrame {

    private JustificarRotinaController controller;
    
    public JustificarRotinaView() {
        controller = new JustificarRotinaController(this);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelRotina = new javax.swing.JLabel();
        jTextFieldRotina = new javax.swing.JTextField();
        jLabelJustificar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaJustificativa = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonJustificar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonReagendar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(0, 51, 65));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 1, 10, new java.awt.Color(151, 158, 0)));

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(240, 240, 240));
        jLabelTitulo.setText("Justificar Rotina");
        jPanel2.add(jLabelTitulo);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(0, 51, 65));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 10, new java.awt.Color(151, 158, 0)));
        jPanel1.setPreferredSize(new java.awt.Dimension(465, 410));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelRotina.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelRotina.setForeground(new java.awt.Color(240, 240, 240));
        jLabelRotina.setText("Rotina:");
        jPanel1.add(jLabelRotina, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jTextFieldRotina.setEditable(false);
        jTextFieldRotina.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(jTextFieldRotina, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 390, -1));

        jLabelJustificar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelJustificar.setForeground(new java.awt.Color(240, 240, 240));
        jLabelJustificar.setText("Justificativa:");
        jPanel1.add(jLabelJustificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jTextAreaJustificativa.setColumns(20);
        jTextAreaJustificativa.setLineWrap(true);
        jTextAreaJustificativa.setRows(5);
        jScrollPane1.setViewportView(jTextAreaJustificativa);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 390, 210));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 430, 10));

        jButtonJustificar.setBackground(new java.awt.Color(151, 158, 0));
        jButtonJustificar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonJustificar.setText("Justificar");
        jPanel1.add(jButtonJustificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        jButtonCancelar.setBackground(new java.awt.Color(151, 158, 0));
        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, -1, -1));

        jButtonReagendar.setBackground(new java.awt.Color(151, 158, 0));
        jButtonReagendar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonReagendar.setText("Reagendar");
        jButtonReagendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReagendarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonReagendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, -1, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonReagendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReagendarActionPerformed
        controller.reagendarRotina();
    }//GEN-LAST:event_jButtonReagendarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        controller.cancelar();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JustificarRotinaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JustificarRotinaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JustificarRotinaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JustificarRotinaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JustificarRotinaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonJustificar;
    private javax.swing.JButton jButtonReagendar;
    private javax.swing.JLabel jLabelJustificar;
    private javax.swing.JLabel jLabelRotina;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextAreaJustificativa;
    private javax.swing.JTextField jTextFieldRotina;
    // End of variables declaration//GEN-END:variables
}
