/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente.principal;

import cliente.login.LoginView;
import javax.swing.JFrame;
import javax.swing.JLabel;
import model.Usuario;

/**
 *
 * @author rafaeld
 */
public class PrincipalView extends javax.swing.JFrame {

    PrincipalController controller;
    
    /**
     * Creates new form PrincipalView
     */
    public PrincipalView() {
        
        initComponents();
        //controller = new PrincipalController(this);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanelCima = new javax.swing.JPanel();
        jLabelAgenda = new javax.swing.JLabel();
        jPanelEsquerda = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jPanelCentro = new javax.swing.JPanel();
        jPanelCentroCima = new javax.swing.JPanel();
        jScrollPaneRotinas = new javax.swing.JScrollPane();
        jTableRotinas = new javax.swing.JTable();
        jPanelBaixo = new javax.swing.JPanel();
        jLabelNome = new javax.swing.JLabel();
        jLabelCargo = new javax.swing.JLabel();
        jLabelUnidade = new javax.swing.JLabel();
        jPanelDireita = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 800));

        jPanelCima.setBackground(new java.awt.Color(0, 54, 65));
        jPanelCima.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(151, 158, 0)));

        jLabelAgenda.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelAgenda.setForeground(new java.awt.Color(240, 240, 240));
        jLabelAgenda.setText("Agenda de Rotinas");
        jPanelCima.add(jLabelAgenda);

        getContentPane().add(jPanelCima, java.awt.BorderLayout.PAGE_START);

        jPanelEsquerda.setBackground(new java.awt.Color(0, 54, 65));
        jPanelEsquerda.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(151, 158, 0), 1, true));

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4.setText("jButton4");
        jPanelEsquerda.add(jButton4);

        getContentPane().add(jPanelEsquerda, java.awt.BorderLayout.LINE_START);

        jPanelCentro.setBackground(new java.awt.Color(0, 54, 65));
        jPanelCentro.setBorder(null);
        jPanelCentro.setLayout(new java.awt.GridLayout(2, 1));

        jPanelCentroCima.setBackground(new java.awt.Color(0, 54, 65));
        jPanelCentroCima.setForeground(new java.awt.Color(0, 54, 65));
        jPanelCentro.add(jPanelCentroCima);

        jScrollPaneRotinas.setPreferredSize(new java.awt.Dimension(400, 350));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jPanelCentro, org.jdesktop.beansbinding.ELProperty.create("${border}"), jScrollPaneRotinas, org.jdesktop.beansbinding.BeanProperty.create("border"));
        bindingGroup.addBinding(binding);

        jTableRotinas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTableRotinas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTableRotinas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"7:00", null, null, null, null, null, null, null},
                {"8:00", null, null, null, null, null, null, null},
                {"9:00", null, null, null, null, null, null, null},
                {"10:00", null, null, null, null, null, null, null},
                {"11:00", null, null, null, null, null, null, null},
                {"12:00", null, null, null, null, null, null, null},
                {"13:00", null, null, null, null, null, null, null},
                {"14:00", null, null, null, null, null, null, null},
                {"15:00", null, null, null, null, null, null, null},
                {"16:00", null, null, null, null, null, null, null},
                {"17:00", null, null, null, null, null, null, null},
                {"18:00", null, null, null, null, null, null, null}
            },
            new String [] {
                "Hora", "Domingo", "Segunda", "Terça", "Quarta", "Quinta", "Sexta", "Sábado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableRotinas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableRotinas.setName(""); // NOI18N
        jTableRotinas.setPreferredSize(new java.awt.Dimension(400, 360));
        jTableRotinas.setRowHeight(30);
        jScrollPaneRotinas.setViewportView(jTableRotinas);
        jTableRotinas.getAccessibleContext().setAccessibleName("");
        jTableRotinas.getAccessibleContext().setAccessibleDescription("");

        jPanelCentro.add(jScrollPaneRotinas);
        jScrollPaneRotinas.getAccessibleContext().setAccessibleName("");

        getContentPane().add(jPanelCentro, java.awt.BorderLayout.CENTER);

        jPanelBaixo.setBackground(new java.awt.Color(0, 54, 65));
        jPanelBaixo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(151, 158, 0), 1, true));
        jPanelBaixo.setLayout(new java.awt.GridLayout(3, 1));

        jLabelNome.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelNome.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNome.setText("Nome");
        jPanelBaixo.add(jLabelNome);

        jLabelCargo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelCargo.setForeground(new java.awt.Color(240, 240, 240));
        jLabelCargo.setText("Cargo");
        jPanelBaixo.add(jLabelCargo);

        jLabelUnidade.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelUnidade.setForeground(new java.awt.Color(240, 240, 240));
        jLabelUnidade.setText("Unidade");
        jPanelBaixo.add(jLabelUnidade);

        getContentPane().add(jPanelBaixo, java.awt.BorderLayout.PAGE_END);

        jPanelDireita.setBackground(new java.awt.Color(0, 54, 65));
        jPanelDireita.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(151, 158, 0), 1, true));

        jButton3.setText("jButton3");
        jPanelDireita.add(jButton3);

        getContentPane().add(jPanelDireita, java.awt.BorderLayout.LINE_END);

        jMenu1.setText("File");

        jMenuItem1.setText("jMenuItem1");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabelAgenda;
    private javax.swing.JLabel jLabelCargo;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelUnidade;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanelBaixo;
    private javax.swing.JPanel jPanelCentro;
    private javax.swing.JPanel jPanelCentroCima;
    private javax.swing.JPanel jPanelCima;
    private javax.swing.JPanel jPanelDireita;
    private javax.swing.JPanel jPanelEsquerda;
    private javax.swing.JScrollPane jScrollPaneRotinas;
    private javax.swing.JTable jTableRotinas;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    
    public void sair(){
        controller.sair();
    }
    
    public void preencheUsuario(){
        controller.preencheUsuario();
    }
    
    public void setUsuario(Usuario usuario){
        controller.setUsuario(usuario);
    }
    
    public Usuario getUsuario(){
        return controller.getUsuario();
    }
    
    
    public JLabel getjLabelCargo() {
        return jLabelCargo;
    }

    public void setjLabelCargo(JLabel jLabelCargo) {
        this.jLabelCargo = jLabelCargo;
    }

    public JLabel getjLabelUnidade() {
        return jLabelUnidade;
    }

    public void setjLabelUnidade(JLabel jLabelUnidade) {
        this.jLabelUnidade = jLabelUnidade;
    }
    public LoginView getLoginView(){
        return controller.getLoginView();
    }
    
    public JLabel getJLabelNome(){
        return jLabelNome;
    }
    
    public void setJLabelNome(JLabel jLabelNome){
        this.jLabelNome = jLabelNome;
    }
    
}
