/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente.principal;

import cliente.login.LoginView;
import javax.swing.JFrame;
import javax.swing.JLabel;
import model.Usuario;

/**
 *
 * @author rafaeld
 */
public class PrincipalView extends javax.swing.JFrame {

    PrincipalController controller;
    
    /**
     * Creates new form PrincipalView
     */
    public PrincipalView() {
        
        initComponents();
        controller = new PrincipalController(this);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        jTableRotinas.setDefaultRenderer(Object.class, new ColorirTabelaRotinas());
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanelCima = new javax.swing.JPanel();
        jLabelAgenda = new javax.swing.JLabel();
        jPanelEsquerda = new javax.swing.JPanel();
        jPanelCentro = new javax.swing.JPanel();
        jPanelCentroCima = new javax.swing.JPanel();
        jPanelCentroCentroCima = new javax.swing.JPanel();
        jLabelRotina = new javax.swing.JLabel();
        jPanelCentralSuperiorInferior = new javax.swing.JPanel();
        jButtonFeitroRotina = new javax.swing.JButton();
        jButtonJustificarRotina = new javax.swing.JButton();
        jButtonDesvincular = new javax.swing.JButton();
        jPanelCentroCentroCentro = new javax.swing.JPanel();
        jLabelNomeRotina = new javax.swing.JLabel();
        jLabelDataRotina = new javax.swing.JLabel();
        jLabelDescricao = new javax.swing.JLabel();
        jScrollPaneDescricao = new javax.swing.JScrollPane();
        jTextAreaDescricao = new javax.swing.JTextArea();
        jTextFieldPeriodoRotina = new javax.swing.JTextField();
        jTextFieldDataRorina = new javax.swing.JTextField();
        jTextFieldHoraRotina = new javax.swing.JTextField();
        jLabelPeriodoRotina = new javax.swing.JLabel();
        jTextFieldEstadoRotina = new javax.swing.JTextField();
        jLabelHoraRotina = new javax.swing.JLabel();
        jTextFieldNomeRotina = new javax.swing.JTextField();
        jLabelEstadoRotina = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonNovaRotina = new javax.swing.JButton();
        jButtonEditarRotina = new javax.swing.JButton();
        jButtonVincularRotina = new javax.swing.JButton();
        jButtonListarRotinas = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jScrollPaneRotinas = new javax.swing.JScrollPane();
        jTableRotinas = new javax.swing.JTable();
        jPanelBaixo = new javax.swing.JPanel();
        jLabelNomeUsuario = new javax.swing.JLabel();
        jLabelCargoUsuario = new javax.swing.JLabel();
        jLabelUnidadeUsuario = new javax.swing.JLabel();
        jPanelDireita = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agenda de Rotinas");
        setMinimumSize(new java.awt.Dimension(1200, 800));

        jPanelCima.setBackground(new java.awt.Color(0, 54, 65));
        jPanelCima.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 10, new java.awt.Color(151, 158, 0)));

        jLabelAgenda.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelAgenda.setForeground(new java.awt.Color(240, 240, 240));
        jLabelAgenda.setText("Agenda de Rotinas");
        jPanelCima.add(jLabelAgenda);

        getContentPane().add(jPanelCima, java.awt.BorderLayout.PAGE_START);

        jPanelEsquerda.setBackground(new java.awt.Color(151, 158, 0));
        jPanelEsquerda.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(151, 158, 0), 1, true));
        getContentPane().add(jPanelEsquerda, java.awt.BorderLayout.LINE_START);

        jPanelCentro.setBackground(new java.awt.Color(0, 54, 65));
        jPanelCentro.setLayout(new java.awt.GridLayout(2, 1));

        jPanelCentroCima.setBackground(new java.awt.Color(0, 54, 65));
        jPanelCentroCima.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 10, 1, new java.awt.Color(151, 158, 0)));
        jPanelCentroCima.setForeground(new java.awt.Color(0, 54, 65));
        jPanelCentroCima.setLayout(new java.awt.BorderLayout());

        jPanelCentroCentroCima.setBackground(new java.awt.Color(0, 54, 65));
        jPanelCentroCentroCima.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(151, 158, 0)));
        jPanelCentroCentroCima.setForeground(new java.awt.Color(240, 240, 240));

        jLabelRotina.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelRotina.setForeground(new java.awt.Color(240, 240, 240));
        jLabelRotina.setText("Rotina A");
        jPanelCentroCentroCima.add(jLabelRotina);

        jPanelCentroCima.add(jPanelCentroCentroCima, java.awt.BorderLayout.PAGE_START);

        jPanelCentralSuperiorInferior.setBackground(new java.awt.Color(0, 51, 64));
        jPanelCentralSuperiorInferior.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(151, 158, 0)));
        jPanelCentralSuperiorInferior.setForeground(new java.awt.Color(240, 240, 240));

        jButtonFeitroRotina.setBackground(new java.awt.Color(151, 158, 0));
        jButtonFeitroRotina.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonFeitroRotina.setText("Feito");
        jPanelCentralSuperiorInferior.add(jButtonFeitroRotina);

        jButtonJustificarRotina.setBackground(new java.awt.Color(151, 158, 0));
        jButtonJustificarRotina.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonJustificarRotina.setText("Justificar");
        jPanelCentralSuperiorInferior.add(jButtonJustificarRotina);

        jButtonDesvincular.setBackground(new java.awt.Color(151, 158, 0));
        jButtonDesvincular.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonDesvincular.setText("Desvincular");
        jPanelCentralSuperiorInferior.add(jButtonDesvincular);

        jPanelCentroCima.add(jPanelCentralSuperiorInferior, java.awt.BorderLayout.PAGE_END);

        jPanelCentroCentroCentro.setBackground(new java.awt.Color(0, 54, 65));
        jPanelCentroCentroCentro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelNomeRotina.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelNomeRotina.setForeground(new java.awt.Color(240, 240, 240));
        jLabelNomeRotina.setText("Nome:");
        jPanelCentroCentroCentro.add(jLabelNomeRotina, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 80, -1));

        jLabelDataRotina.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelDataRotina.setForeground(new java.awt.Color(240, 240, 240));
        jLabelDataRotina.setText("Data:");
        jPanelCentroCentroCentro.add(jLabelDataRotina, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabelDescricao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelDescricao.setForeground(new java.awt.Color(240, 240, 240));
        jLabelDescricao.setText("Descrição:");
        jPanelCentroCentroCentro.add(jLabelDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, -1, 20));

        jTextAreaDescricao.setColumns(20);
        jTextAreaDescricao.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jTextAreaDescricao.setLineWrap(true);
        jTextAreaDescricao.setRows(5);
        jScrollPaneDescricao.setViewportView(jTextAreaDescricao);

        jPanelCentroCentroCentro.add(jScrollPaneDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 40, 760, 200));

        jTextFieldPeriodoRotina.setEditable(false);
        jTextFieldPeriodoRotina.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldPeriodoRotina.setText("Diário");
        jTextFieldPeriodoRotina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPeriodoRotinaActionPerformed(evt);
            }
        });
        jPanelCentroCentroCentro.add(jTextFieldPeriodoRotina, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 270, 25));

        jTextFieldDataRorina.setEditable(false);
        jTextFieldDataRorina.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldDataRorina.setText("7/10/2021");
        jTextFieldDataRorina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDataRorinaActionPerformed(evt);
            }
        });
        jPanelCentroCentroCentro.add(jTextFieldDataRorina, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 267, 25));

        jTextFieldHoraRotina.setEditable(false);
        jTextFieldHoraRotina.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldHoraRotina.setText("7h");
        jTextFieldHoraRotina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHoraRotinaActionPerformed(evt);
            }
        });
        jPanelCentroCentroCentro.add(jTextFieldHoraRotina, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 270, -1));

        jLabelPeriodoRotina.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelPeriodoRotina.setForeground(new java.awt.Color(240, 240, 240));
        jLabelPeriodoRotina.setText("Periodo:");
        jPanelCentroCentroCentro.add(jLabelPeriodoRotina, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 80, -1));

        jTextFieldEstadoRotina.setEditable(false);
        jTextFieldEstadoRotina.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldEstadoRotina.setText("Em Vigor");
        jTextFieldEstadoRotina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEstadoRotinaActionPerformed(evt);
            }
        });
        jPanelCentroCentroCentro.add(jTextFieldEstadoRotina, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 270, -1));

        jLabelHoraRotina.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelHoraRotina.setForeground(new java.awt.Color(240, 240, 240));
        jLabelHoraRotina.setText("Horários:");
        jPanelCentroCentroCentro.add(jLabelHoraRotina, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jTextFieldNomeRotina.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldNomeRotina.setText("Rotina A");
        jPanelCentroCentroCentro.add(jTextFieldNomeRotina, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 270, -1));

        jLabelEstadoRotina.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelEstadoRotina.setForeground(new java.awt.Color(240, 240, 240));
        jLabelEstadoRotina.setText("Estado: ");
        jPanelCentroCentroCentro.add(jLabelEstadoRotina, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        jPanelCentroCima.add(jPanelCentroCentroCentro, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(0, 51, 64));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(151, 158, 0)));
        jPanel2.setLayout(new java.awt.GridLayout(5, 1, 5, 5));

        jButtonNovaRotina.setBackground(new java.awt.Color(151, 154, 0));
        jButtonNovaRotina.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonNovaRotina.setText("Nova");
        jButtonNovaRotina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovaRotinaActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonNovaRotina);

        jButtonEditarRotina.setBackground(new java.awt.Color(151, 154, 0));
        jButtonEditarRotina.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonEditarRotina.setText("Editar");
        jButtonEditarRotina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarRotinaActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonEditarRotina);

        jButtonVincularRotina.setBackground(new java.awt.Color(151, 154, 0));
        jButtonVincularRotina.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonVincularRotina.setText("Vincular");
        jButtonVincularRotina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVincularRotinaActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonVincularRotina);

        jButtonListarRotinas.setBackground(new java.awt.Color(151, 154, 0));
        jButtonListarRotinas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonListarRotinas.setText("Listar");
        jButtonListarRotinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarRotinasActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonListarRotinas);

        jButtonSair.setBackground(new java.awt.Color(151, 154, 0));
        jButtonSair.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonSair);

        jPanelCentroCima.add(jPanel2, java.awt.BorderLayout.LINE_START);

        jPanelCentro.add(jPanelCentroCima);

        jScrollPaneRotinas.setPreferredSize(new java.awt.Dimension(400, 350));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jPanelCentro, org.jdesktop.beansbinding.ELProperty.create("${border}"), jScrollPaneRotinas, org.jdesktop.beansbinding.BeanProperty.create("border"));
        bindingGroup.addBinding(binding);

        jTableRotinas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTableRotinas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTableRotinas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"7:00", null, "Rotina A", "Rotina A", null, null, null, null},
                {"8:00", null, null, "Rotina B", null, null, null, null},
                {"9:00", null, null, "Rotina C", null, null, null, null},
                {"10:00", null, null, null, null, null, null, null},
                {"11:00", null, null, null, null, null, null, null},
                {"12:00", null, null, null, null, null, null, null},
                {"13:00", null, null, null, null, null, null, null},
                {"14:00", null, null, null, null, null, null, null},
                {"15:00", null, null, null, null, null, null, null},
                {"16:00", null, null, null, null, null, null, null},
                {"17:00", null, null, null, null, null, null, null},
                {"18:00", null, null, null, null, null, null, null}
            },
            new String [] {
                "Hora", "Domingo", "Segunda", "Terça", "Quarta", "Quinta", "Sexta", "Sábado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableRotinas.setToolTipText("");
        jTableRotinas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableRotinas.setName(""); // NOI18N
        jTableRotinas.setPreferredSize(new java.awt.Dimension(400, 360));
        jTableRotinas.setRowHeight(30);
        jScrollPaneRotinas.setViewportView(jTableRotinas);
        jTableRotinas.getAccessibleContext().setAccessibleName("");

        jPanelCentro.add(jScrollPaneRotinas);
        jScrollPaneRotinas.getAccessibleContext().setAccessibleName("");

        getContentPane().add(jPanelCentro, java.awt.BorderLayout.CENTER);

        jPanelBaixo.setBackground(new java.awt.Color(0, 54, 65));
        jPanelBaixo.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 10, new java.awt.Color(151, 158, 0)));
        jPanelBaixo.setLayout(new java.awt.GridLayout(3, 1));

        jLabelNomeUsuario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelNomeUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNomeUsuario.setText("Nome");
        jPanelBaixo.add(jLabelNomeUsuario);

        jLabelCargoUsuario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelCargoUsuario.setForeground(new java.awt.Color(240, 240, 240));
        jLabelCargoUsuario.setText("Cargo");
        jPanelBaixo.add(jLabelCargoUsuario);

        jLabelUnidadeUsuario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelUnidadeUsuario.setForeground(new java.awt.Color(240, 240, 240));
        jLabelUnidadeUsuario.setText("Unidade");
        jPanelBaixo.add(jLabelUnidadeUsuario);

        getContentPane().add(jPanelBaixo, java.awt.BorderLayout.PAGE_END);

        jPanelDireita.setBackground(new java.awt.Color(151, 158, 0));
        getContentPane().add(jPanelDireita, java.awt.BorderLayout.LINE_END);

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDataRorinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDataRorinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDataRorinaActionPerformed

    private void jTextFieldPeriodoRotinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPeriodoRotinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPeriodoRotinaActionPerformed

    private void jTextFieldHoraRotinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHoraRotinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHoraRotinaActionPerformed

    private void jTextFieldEstadoRotinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEstadoRotinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEstadoRotinaActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        controller.sair();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonNovaRotinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovaRotinaActionPerformed
        controller.novaRotina();
    }//GEN-LAST:event_jButtonNovaRotinaActionPerformed

    private void jButtonEditarRotinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarRotinaActionPerformed
        controller.editarRotina();
    }//GEN-LAST:event_jButtonEditarRotinaActionPerformed

    private void jButtonVincularRotinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVincularRotinaActionPerformed
        controller.vincularRotina();
    }//GEN-LAST:event_jButtonVincularRotinaActionPerformed

    private void jButtonListarRotinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarRotinasActionPerformed
        controller.listarRotina();
    }//GEN-LAST:event_jButtonListarRotinasActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDesvincular;
    private javax.swing.JButton jButtonEditarRotina;
    private javax.swing.JButton jButtonFeitroRotina;
    private javax.swing.JButton jButtonJustificarRotina;
    private javax.swing.JButton jButtonListarRotinas;
    private javax.swing.JButton jButtonNovaRotina;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonVincularRotina;
    private javax.swing.JLabel jLabelAgenda;
    private javax.swing.JLabel jLabelCargoUsuario;
    private javax.swing.JLabel jLabelDataRotina;
    private javax.swing.JLabel jLabelDescricao;
    private javax.swing.JLabel jLabelEstadoRotina;
    private javax.swing.JLabel jLabelHoraRotina;
    private javax.swing.JLabel jLabelNomeRotina;
    private javax.swing.JLabel jLabelNomeUsuario;
    private javax.swing.JLabel jLabelPeriodoRotina;
    private javax.swing.JLabel jLabelRotina;
    private javax.swing.JLabel jLabelUnidadeUsuario;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelBaixo;
    private javax.swing.JPanel jPanelCentralSuperiorInferior;
    private javax.swing.JPanel jPanelCentro;
    private javax.swing.JPanel jPanelCentroCentroCentro;
    private javax.swing.JPanel jPanelCentroCentroCima;
    private javax.swing.JPanel jPanelCentroCima;
    private javax.swing.JPanel jPanelCima;
    private javax.swing.JPanel jPanelDireita;
    private javax.swing.JPanel jPanelEsquerda;
    private javax.swing.JScrollPane jScrollPaneDescricao;
    private javax.swing.JScrollPane jScrollPaneRotinas;
    private javax.swing.JTable jTableRotinas;
    private javax.swing.JTextArea jTextAreaDescricao;
    private javax.swing.JTextField jTextFieldDataRorina;
    private javax.swing.JTextField jTextFieldEstadoRotina;
    private javax.swing.JTextField jTextFieldHoraRotina;
    private javax.swing.JTextField jTextFieldNomeRotina;
    private javax.swing.JTextField jTextFieldPeriodoRotina;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    
    public void sair(){
        controller.sair();
    }
    
    public void preencheUsuario(){
        controller.preencheUsuario();
    }
    
    public void setUsuario(Usuario usuario){
        controller.setUsuario(usuario);
    }
    
    public Usuario getUsuario(){
        return controller.getUsuario();
    }
    
    
    public JLabel getjLabelCargo() {
        return jLabelCargoUsuario;
    }

    public void setjLabelCargo(JLabel jLabelCargo) {
        this.jLabelCargoUsuario = jLabelCargo;
    }

    public JLabel getjLabelUnidade() {
        return jLabelUnidadeUsuario;
    }

    public void setjLabelUnidade(JLabel jLabelUnidade) {
        this.jLabelUnidadeUsuario = jLabelUnidade;
    }
    public LoginView getLoginView(){
        return controller.getLoginView();
    }
    
    public JLabel getJLabelNome(){
        return jLabelNomeUsuario;
    }
    
    public void setJLabelNome(JLabel jLabelNome){
        this.jLabelNomeUsuario = jLabelNome;
    }
    
}
