/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente.agendarrotina;

/**
 *
 * @author rafaeld
 */
public class AgendarRotinaView extends javax.swing.JFrame {

    private AgendarRotinaController controller;
    
    public AgendarRotinaView() {
        controller = new AgendarRotinaController(this);
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTopo = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jPanelCentro = new javax.swing.JPanel();
        jLabelRotina = new javax.swing.JLabel();
        jTextFieldRotina = new javax.swing.JTextField();
        jLabelHora = new javax.swing.JLabel();
        jTextFieldHora = new javax.swing.JTextField();
        jComboBoxHora = new javax.swing.JComboBox<>();
        jButtonRetirarHora = new javax.swing.JButton();
        jLabelData = new javax.swing.JLabel();
        jTextFieldData = new javax.swing.JTextField();
        jButtonAgendar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanelTopo.setBackground(new java.awt.Color(0, 51, 65));
        jPanelTopo.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 1, 10, new java.awt.Color(151, 158, 0)));

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(240, 240, 240));
        jLabelTitulo.setText("Agendar Rotina");
        jPanelTopo.add(jLabelTitulo);

        getContentPane().add(jPanelTopo, java.awt.BorderLayout.PAGE_START);

        jPanelCentro.setBackground(new java.awt.Color(0, 51, 65));
        jPanelCentro.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 10, new java.awt.Color(151, 158, 0)));
        jPanelCentro.setPreferredSize(new java.awt.Dimension(400, 300));
        jPanelCentro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelRotina.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelRotina.setForeground(new java.awt.Color(240, 240, 240));
        jLabelRotina.setText("Rotina:");
        jPanelCentro.add(jLabelRotina, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jTextFieldRotina.setEditable(false);
        jTextFieldRotina.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanelCentro.add(jTextFieldRotina, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 320, -1));

        jLabelHora.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelHora.setForeground(new java.awt.Color(240, 240, 240));
        jLabelHora.setText("Hora:");
        jPanelCentro.add(jLabelHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jTextFieldHora.setEditable(false);
        jTextFieldHora.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanelCentro.add(jTextFieldHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 320, -1));

        jComboBoxHora.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBoxHora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "7h", "8h", "9h", "10h", "11h", "12h", "13h", "14h", "15h", "16h", "17h", "18h" }));
        jPanelCentro.add(jComboBoxHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 60, -1));

        jButtonRetirarHora.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonRetirarHora.setText("<--");
        jPanelCentro.add(jButtonRetirarHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, -1));

        jLabelData.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelData.setForeground(new java.awt.Color(240, 240, 240));
        jLabelData.setText("Data:");
        jPanelCentro.add(jLabelData, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jTextFieldData.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanelCentro.add(jTextFieldData, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 320, -1));

        jButtonAgendar.setBackground(new java.awt.Color(151, 158, 0));
        jButtonAgendar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonAgendar.setText("Agendar");
        jPanelCentro.add(jButtonAgendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        jButtonCancelar.setBackground(new java.awt.Color(151, 158, 0));
        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jPanelCentro.add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, -1, -1));
        jPanelCentro.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 360, 20));

        getContentPane().add(jPanelCentro, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        controller.cancelar();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgendarRotinaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgendarRotinaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgendarRotinaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgendarRotinaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgendarRotinaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgendar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonRetirarHora;
    private javax.swing.JComboBox<String> jComboBoxHora;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelHora;
    private javax.swing.JLabel jLabelRotina;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanelCentro;
    private javax.swing.JPanel jPanelTopo;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldData;
    private javax.swing.JTextField jTextFieldHora;
    private javax.swing.JTextField jTextFieldRotina;
    // End of variables declaration//GEN-END:variables
}
