/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente.salvarrotina;

/**
 *
 * @author rafaeld
 */
public class SalvarRotinaView extends javax.swing.JFrame {

    /**
     * Creates new form NovaRotinaView
     */
    public SalvarRotinaView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanelPrincipal = new javax.swing.JPanel();
        jPanelFundo = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescricao = new javax.swing.JTextArea();
        jTextFieldNomeRotina = new javax.swing.JTextField();
        jLabelDescricao = new javax.swing.JLabel();
        jLabelNomeRotina = new javax.swing.JLabel();
        jLabelUnidade = new javax.swing.JLabel();
        jButtonCadastrar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabelPeriodo = new javax.swing.JLabel();
        jComboBoxPeriodo = new javax.swing.JComboBox<>();
        jComboBoxUnidade = new javax.swing.JComboBox<>();
        jLabelDataLimite = new javax.swing.JLabel();
        jComboBoxDataLimite = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jPanelTopo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelPrincipal.setBackground(new java.awt.Color(0, 54, 65));
        jPanelPrincipal.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 10, new java.awt.Color(151, 158, 0)));
        jPanelPrincipal.setLayout(new java.awt.BorderLayout());

        jPanelFundo.setBackground(new java.awt.Color(0, 54, 65));
        jPanelFundo.setMinimumSize(new java.awt.Dimension(760, 340));
        jPanelFundo.setPreferredSize(new java.awt.Dimension(750, 345));
        jPanelFundo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextAreaDescricao.setColumns(20);
        jTextAreaDescricao.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDescricao);

        jPanelFundo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 370, 240));

        jTextFieldNomeRotina.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextFieldNomeRotina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeRotinaActionPerformed(evt);
            }
        });
        jPanelFundo.add(jTextFieldNomeRotina, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 260, -1));

        jLabelDescricao.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelDescricao.setForeground(new java.awt.Color(240, 240, 240));
        jLabelDescricao.setText("Descrição:");
        jPanelFundo.add(jLabelDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, 20));

        jLabelNomeRotina.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelNomeRotina.setForeground(new java.awt.Color(240, 240, 240));
        jLabelNomeRotina.setText("Nome:");
        jPanelFundo.add(jLabelNomeRotina, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jLabelUnidade.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelUnidade.setForeground(new java.awt.Color(240, 240, 240));
        jLabelUnidade.setText("Unidade:");
        jPanelFundo.add(jLabelUnidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jButtonCadastrar.setBackground(new java.awt.Color(151, 158, 0));
        jButtonCadastrar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonCadastrar.setText("Salvar");
        jPanelFundo.add(jButtonCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, -1, -1));

        jButtonCancelar.setBackground(new java.awt.Color(151, 158, 0));
        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jPanelFundo.add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, -1, -1));

        jLabelPeriodo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelPeriodo.setForeground(new java.awt.Color(240, 240, 240));
        jLabelPeriodo.setText("Período:");
        jPanelFundo.add(jLabelPeriodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jComboBoxPeriodo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jComboBoxPeriodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Diário", "Semanal", "Mensal", "Único" }));
        jPanelFundo.add(jComboBoxPeriodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 260, -1));

        jComboBoxUnidade.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jComboBoxUnidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Técnologia", "Crédito" }));
        jPanelFundo.add(jComboBoxUnidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 260, -1));

        jLabelDataLimite.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelDataLimite.setForeground(new java.awt.Color(240, 240, 240));
        jLabelDataLimite.setText("Data Limite:");
        jPanelFundo.add(jLabelDataLimite, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jComboBoxDataLimite.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanelFundo.add(jComboBoxDataLimite, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 260, -1));
        jPanelFundo.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 730, 10));

        jPanelPrincipal.add(jPanelFundo, java.awt.BorderLayout.CENTER);

        jPanelTopo.setBackground(new java.awt.Color(0, 54, 65));
        jPanelTopo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 10, 0, new java.awt.Color(151, 158, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Salvar Rotina");
        jPanelTopo.add(jLabel1);

        jPanelPrincipal.add(jPanelTopo, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanelPrincipal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNomeRotinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeRotinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeRotinaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalvarRotinaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalvarRotinaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalvarRotinaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalvarRotinaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalvarRotinaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JComboBox<String> jComboBoxDataLimite;
    private javax.swing.JComboBox<String> jComboBoxPeriodo;
    private javax.swing.JComboBox<String> jComboBoxUnidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelDataLimite;
    private javax.swing.JLabel jLabelDescricao;
    private javax.swing.JLabel jLabelNomeRotina;
    private javax.swing.JLabel jLabelPeriodo;
    private javax.swing.JLabel jLabelUnidade;
    private javax.swing.JPanel jPanelFundo;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JPanel jPanelTopo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextAreaDescricao;
    private javax.swing.JTextField jTextFieldNomeRotina;
    // End of variables declaration//GEN-END:variables
}
