/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente.vincularrotina;

/**
 *
 * @author rafaeld
 */
public class VincularRotinaView extends javax.swing.JFrame {

    /**
     * Creates new form VincularRotinaView
     */
    public VincularRotinaView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupReagendavel = new javax.swing.ButtonGroup();
        buttonGroupPrioritario = new javax.swing.ButtonGroup();
        buttonGrouHoraFixa = new javax.swing.ButtonGroup();
        jPanelPrincipal = new javax.swing.JPanel();
        jPanelFundo = new javax.swing.JPanel();
        jLabelRotina = new javax.swing.JLabel();
        jLabelUnidade = new javax.swing.JLabel();
        jComboBoxPeriodo = new javax.swing.JComboBox<>();
        jComboBoxRotina = new javax.swing.JComboBox<>();
        jLabelFuncionario = new javax.swing.JLabel();
        jComboBoxFuncionario = new javax.swing.JComboBox<>();
        jLabelData = new javax.swing.JLabel();
        jComboBoxUnidade = new javax.swing.JComboBox<>();
        jLabelHora = new javax.swing.JLabel();
        jComboBoxData = new javax.swing.JComboBox<>();
        jLabelObservacao = new javax.swing.JLabel();
        jButtonRegistrar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabelPeriodo = new javax.swing.JLabel();
        jComboBoxHora = new javax.swing.JComboBox<>();
        jTextFieldHora = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanelReagendavel = new javax.swing.JPanel();
        jRadioButtonReagendavelNao = new javax.swing.JRadioButton();
        jRadioButtonReagendavelSim = new javax.swing.JRadioButton();
        jLabelReagendavel = new javax.swing.JLabel();
        jPanelPrioritario = new javax.swing.JPanel();
        jLabelPrioritario = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jPanelHoraFixa = new javax.swing.JPanel();
        jLabelHoraFixa = new javax.swing.JLabel();
        jRadioButtonHoraFixaSim = new javax.swing.JRadioButton();
        jRadioButtonHoraFixaNao = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaObservacao = new javax.swing.JTextArea();
        jPanelTopo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelPrincipal.setBackground(new java.awt.Color(0, 51, 65));
        jPanelPrincipal.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 10, new java.awt.Color(151, 158, 0)));
        jPanelPrincipal.setLayout(new java.awt.BorderLayout());

        jPanelFundo.setBackground(new java.awt.Color(0, 51, 65));
        jPanelFundo.setPreferredSize(new java.awt.Dimension(495, 630));
        jPanelFundo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelRotina.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelRotina.setForeground(new java.awt.Color(240, 240, 240));
        jLabelRotina.setText("Rotina:");
        jPanelFundo.add(jLabelRotina, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabelUnidade.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelUnidade.setForeground(new java.awt.Color(240, 240, 240));
        jLabelUnidade.setText("Unidade:");
        jPanelFundo.add(jLabelUnidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jComboBoxPeriodo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanelFundo.add(jComboBoxPeriodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 180, -1));

        jComboBoxRotina.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanelFundo.add(jComboBoxRotina, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 180, -1));

        jLabelFuncionario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelFuncionario.setForeground(new java.awt.Color(240, 240, 240));
        jLabelFuncionario.setText("Funcionário:");
        jPanelFundo.add(jLabelFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jComboBoxFuncionario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanelFundo.add(jComboBoxFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 180, -1));

        jLabelData.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelData.setForeground(new java.awt.Color(240, 240, 240));
        jLabelData.setText("Data(s):");
        jPanelFundo.add(jLabelData, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, -1, -1));

        jComboBoxUnidade.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanelFundo.add(jComboBoxUnidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 180, -1));

        jLabelHora.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelHora.setForeground(new java.awt.Color(240, 240, 240));
        jLabelHora.setText("Hora:");
        jPanelFundo.add(jLabelHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, -1, -1));

        jComboBoxData.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanelFundo.add(jComboBoxData, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 180, -1));

        jLabelObservacao.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelObservacao.setForeground(new java.awt.Color(240, 240, 240));
        jLabelObservacao.setText("Observação:");
        jPanelFundo.add(jLabelObservacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, -1));

        jButtonRegistrar.setBackground(new java.awt.Color(151, 158, 0));
        jButtonRegistrar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonRegistrar.setText("Registrar");
        jButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarActionPerformed(evt);
            }
        });
        jPanelFundo.add(jButtonRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 590, -1, -1));

        jButtonCancelar.setBackground(new java.awt.Color(151, 158, 0));
        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setToolTipText("");
        jPanelFundo.add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 590, -1, -1));

        jLabelPeriodo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelPeriodo.setForeground(new java.awt.Color(240, 240, 240));
        jLabelPeriodo.setText("Período:");
        jPanelFundo.add(jLabelPeriodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jComboBoxHora.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBoxHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxHoraActionPerformed(evt);
            }
        });
        jPanelFundo.add(jComboBoxHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 70, 20));

        jTextFieldHora.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanelFundo.add(jTextFieldHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 180, 30));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("<--");
        jPanelFundo.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 60, 20));

        jSeparator1.setBackground(new java.awt.Color(151, 158, 0));
        jSeparator1.setForeground(new java.awt.Color(240, 240, 240));
        jPanelFundo.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, 460, 10));

        jPanelReagendavel.setBackground(new java.awt.Color(0, 51, 65));
        jPanelReagendavel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(240, 240, 240)));
        jPanelReagendavel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroupReagendavel.add(jRadioButtonReagendavelNao);
        jRadioButtonReagendavelNao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButtonReagendavelNao.setForeground(new java.awt.Color(240, 240, 240));
        jRadioButtonReagendavelNao.setText("Não");
        jRadioButtonReagendavelNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonReagendavelNaoActionPerformed(evt);
            }
        });
        jPanelReagendavel.add(jRadioButtonReagendavelNao, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 60, -1));

        buttonGroupReagendavel.add(jRadioButtonReagendavelSim);
        jRadioButtonReagendavelSim.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButtonReagendavelSim.setForeground(new java.awt.Color(240, 240, 240));
        jRadioButtonReagendavelSim.setText("Sim");
        jPanelReagendavel.add(jRadioButtonReagendavelSim, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 60, -1));

        jLabelReagendavel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelReagendavel.setForeground(new java.awt.Color(240, 240, 240));
        jLabelReagendavel.setText("Reagendável:");
        jPanelReagendavel.add(jLabelReagendavel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanelFundo.add(jPanelReagendavel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 180, 70));

        jPanelPrioritario.setBackground(new java.awt.Color(0, 51, 65));
        jPanelPrioritario.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(240, 240, 240)));
        jPanelPrioritario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelPrioritario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelPrioritario.setForeground(new java.awt.Color(240, 240, 240));
        jLabelPrioritario.setText("Prioritário:");
        jPanelPrioritario.add(jLabelPrioritario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        buttonGroupPrioritario.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(240, 240, 240));
        jRadioButton1.setText("Sim");
        jPanelPrioritario.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 60, -1));

        buttonGroupPrioritario.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(240, 240, 240));
        jRadioButton2.setText("Não");
        jPanelPrioritario.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 60, -1));

        jPanelFundo.add(jPanelPrioritario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 180, 70));

        jPanelHoraFixa.setBackground(new java.awt.Color(0, 51, 65));
        jPanelHoraFixa.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(240, 240, 240)));
        jPanelHoraFixa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelHoraFixa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelHoraFixa.setForeground(new java.awt.Color(240, 240, 240));
        jLabelHoraFixa.setText("Horário Fixo");
        jPanelHoraFixa.add(jLabelHoraFixa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 130, 30));

        buttonGrouHoraFixa.add(jRadioButtonHoraFixaSim);
        jRadioButtonHoraFixaSim.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButtonHoraFixaSim.setForeground(new java.awt.Color(240, 240, 240));
        jRadioButtonHoraFixaSim.setText("Sim");
        jRadioButtonHoraFixaSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonHoraFixaSimActionPerformed(evt);
            }
        });
        jPanelHoraFixa.add(jRadioButtonHoraFixaSim, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 60, -1));

        buttonGrouHoraFixa.add(jRadioButtonHoraFixaNao);
        jRadioButtonHoraFixaNao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButtonHoraFixaNao.setForeground(new java.awt.Color(240, 240, 240));
        jRadioButtonHoraFixaNao.setText("Não");
        jPanelHoraFixa.add(jRadioButtonHoraFixaNao, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 60, -1));

        jPanelFundo.add(jPanelHoraFixa, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 180, 70));

        jTextAreaObservacao.setColumns(20);
        jTextAreaObservacao.setRows(5);
        jScrollPane1.setViewportView(jTextAreaObservacao);

        jPanelFundo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 410, 120));

        jPanelPrincipal.add(jPanelFundo, java.awt.BorderLayout.CENTER);

        jPanelTopo.setBackground(new java.awt.Color(0, 51, 65));
        jPanelTopo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 10, 0, new java.awt.Color(151, 154, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Vincular Rotina");
        jPanelTopo.add(jLabel1);

        jPanelPrincipal.add(jPanelTopo, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanelPrincipal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRegistrarActionPerformed

    private void jComboBoxHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxHoraActionPerformed

    private void jRadioButtonReagendavelNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonReagendavelNaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonReagendavelNaoActionPerformed

    private void jRadioButtonHoraFixaSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonHoraFixaSimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonHoraFixaSimActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VincularRotinaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VincularRotinaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VincularRotinaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VincularRotinaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VincularRotinaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGrouHoraFixa;
    private javax.swing.ButtonGroup buttonGroupPrioritario;
    private javax.swing.ButtonGroup buttonGroupReagendavel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JComboBox<String> jComboBoxData;
    private javax.swing.JComboBox<String> jComboBoxFuncionario;
    private javax.swing.JComboBox<String> jComboBoxHora;
    private javax.swing.JComboBox<String> jComboBoxPeriodo;
    private javax.swing.JComboBox<String> jComboBoxRotina;
    private javax.swing.JComboBox<String> jComboBoxUnidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelFuncionario;
    private javax.swing.JLabel jLabelHora;
    private javax.swing.JLabel jLabelHoraFixa;
    private javax.swing.JLabel jLabelObservacao;
    private javax.swing.JLabel jLabelPeriodo;
    private javax.swing.JLabel jLabelPrioritario;
    private javax.swing.JLabel jLabelReagendavel;
    private javax.swing.JLabel jLabelRotina;
    private javax.swing.JLabel jLabelUnidade;
    private javax.swing.JPanel jPanelFundo;
    private javax.swing.JPanel jPanelHoraFixa;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JPanel jPanelPrioritario;
    private javax.swing.JPanel jPanelReagendavel;
    private javax.swing.JPanel jPanelTopo;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButtonHoraFixaNao;
    private javax.swing.JRadioButton jRadioButtonHoraFixaSim;
    private javax.swing.JRadioButton jRadioButtonReagendavelNao;
    private javax.swing.JRadioButton jRadioButtonReagendavelSim;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextAreaObservacao;
    private javax.swing.JTextField jTextFieldHora;
    // End of variables declaration//GEN-END:variables
}
