/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente.vincularrotina;

import java.util.Calendar;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import util.date.Calendario;


/**
 *
 * @author rafaeld
 */
public class VincularRotinaView extends javax.swing.JFrame {

    private VincularRotinaController controller;
    
    public VincularRotinaView() {
        initComponents();
        controller = new VincularRotinaController(this);
        preencherAno();
        preencherDia();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jPanelPrincipal = new javax.swing.JPanel();
        jPanelFundo = new javax.swing.JPanel();
        jLabelRotina = new javax.swing.JLabel();
        jLabelUnidade = new javax.swing.JLabel();
        jComboBoxPeriodo = new javax.swing.JComboBox<>();
        jComboBoxRotina = new javax.swing.JComboBox<>();
        jLabelFuncionario = new javax.swing.JLabel();
        jComboBoxFuncionario = new javax.swing.JComboBox<>();
        jComboBoxUnidade = new javax.swing.JComboBox<>();
        jLabelHora = new javax.swing.JLabel();
        jLabelObservacao = new javax.swing.JLabel();
        jButtonVincular = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabelPeriodo = new javax.swing.JLabel();
        jButtonApagaHora = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPaneObeservacao = new javax.swing.JScrollPane();
        jTextAreaObservacao = new javax.swing.JTextArea();
        jLabelDias = new javax.swing.JLabel();
        jComboBoxMes = new javax.swing.JComboBox<>();
        jButtonApagaMes = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxDia = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxDiaSemana = new javax.swing.JComboBox<>();
        jButtonApagaDiaSemana = new javax.swing.JButton();
        jLabelDiasUtil = new javax.swing.JLabel();
        jComboBoxDiaUtil = new javax.swing.JComboBox<>();
        jButtonApagaDiaUtil = new javax.swing.JButton();
        jCheckBoxReagendavel = new javax.swing.JCheckBox();
        jCheckBoxPrioritario = new javax.swing.JCheckBox();
        jCheckBoxHorarioFixo = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListDiaSemana = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListMes = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListHorario = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListDiaUtil = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        jListDia = new javax.swing.JList<>();
        jButtonApagaDia = new javax.swing.JButton();
        jComboBoxHora = new javax.swing.JComboBox<>();
        jLabelAno = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jListAno = new javax.swing.JList<>();
        jComboBoxAno = new javax.swing.JComboBox<>();
        jButtonApagaAno = new javax.swing.JButton();
        jButtonPeriodoInterrogacao = new javax.swing.JButton();
        jButtonPrioritarioInterrogacao = new javax.swing.JButton();
        jButtonReagendavelInterrogacao = new javax.swing.JButton();
        jButtonHorarioFixoInterrogacao = new javax.swing.JButton();
        jPanelTopo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jLabel4.setText("Teste");
        jDialog1.getContentPane().add(jLabel4, java.awt.BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Vincular Rotina");
        setMinimumSize(new java.awt.Dimension(1190, 640));
        setPreferredSize(new java.awt.Dimension(1380, 650));
        setResizable(false);

        jPanelPrincipal.setBackground(new java.awt.Color(0, 51, 65));
        jPanelPrincipal.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 10, new java.awt.Color(151, 158, 0)));
        jPanelPrincipal.setMinimumSize(new java.awt.Dimension(1190, 630));
        jPanelPrincipal.setPreferredSize(new java.awt.Dimension(1190, 630));
        jPanelPrincipal.setLayout(new java.awt.BorderLayout());

        jPanelFundo.setBackground(new java.awt.Color(0, 51, 65));
        jPanelFundo.setMinimumSize(new java.awt.Dimension(1170, 560));
        jPanelFundo.setPreferredSize(new java.awt.Dimension(1360, 570));
        jPanelFundo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelRotina.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelRotina.setForeground(new java.awt.Color(240, 240, 240));
        jLabelRotina.setText("Rotina:");
        jPanelFundo.add(jLabelRotina, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabelUnidade.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelUnidade.setForeground(new java.awt.Color(240, 240, 240));
        jLabelUnidade.setText("Unidade:");
        jPanelFundo.add(jLabelUnidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jComboBoxPeriodo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBoxPeriodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Data Única", "Diário", "Semanal", "Dia Útil/Mês", "Dia/Mês", "Datas/Ano", "Anual" }));
        jComboBoxPeriodo.setToolTipText("");
        jComboBoxPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPeriodoActionPerformed(evt);
            }
        });
        jPanelFundo.add(jComboBoxPeriodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 250, 30));

        jComboBoxRotina.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBoxRotina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tecnologia da Informação" }));
        jComboBoxRotina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxRotinaActionPerformed(evt);
            }
        });
        jPanelFundo.add(jComboBoxRotina, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 250, 30));

        jLabelFuncionario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelFuncionario.setForeground(new java.awt.Color(240, 240, 240));
        jLabelFuncionario.setText("Funcionário:");
        jPanelFundo.add(jLabelFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jComboBoxFuncionario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBoxFuncionario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "João Carlos" }));
        jPanelFundo.add(jComboBoxFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 250, 30));

        jComboBoxUnidade.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBoxUnidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rotina A", "Rotina B", "Rotina C" }));
        jPanelFundo.add(jComboBoxUnidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 250, 30));

        jLabelHora.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelHora.setForeground(new java.awt.Color(240, 240, 240));
        jLabelHora.setText("Horários:");
        jPanelFundo.add(jLabelHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 270, -1, -1));

        jLabelObservacao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelObservacao.setForeground(new java.awt.Color(240, 240, 240));
        jLabelObservacao.setText("Observação:");
        jPanelFundo.add(jLabelObservacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, -1, -1));

        jButtonVincular.setBackground(new java.awt.Color(151, 158, 0));
        jButtonVincular.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonVincular.setText("Vincular");
        jButtonVincular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVincularActionPerformed(evt);
            }
        });
        jPanelFundo.add(jButtonVincular, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 510, -1, -1));

        jButtonCancelar.setBackground(new java.awt.Color(151, 158, 0));
        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setToolTipText("");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jPanelFundo.add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 510, -1, -1));

        jLabelPeriodo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelPeriodo.setForeground(new java.awt.Color(240, 240, 240));
        jLabelPeriodo.setText("Período:");
        jPanelFundo.add(jLabelPeriodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jButtonApagaHora.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonApagaHora.setText("<--");
        jButtonApagaHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApagaHoraActionPerformed(evt);
            }
        });
        jPanelFundo.add(jButtonApagaHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 320, 50, 25));

        jSeparator1.setBackground(new java.awt.Color(151, 158, 0));
        jSeparator1.setForeground(new java.awt.Color(240, 240, 240));
        jPanelFundo.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 1320, 10));

        jTextAreaObservacao.setColumns(20);
        jTextAreaObservacao.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jTextAreaObservacao.setRows(5);
        jScrollPaneObeservacao.setViewportView(jTextAreaObservacao);

        jPanelFundo.add(jScrollPaneObeservacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, 810, 180));

        jLabelDias.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelDias.setForeground(new java.awt.Color(240, 240, 240));
        jLabelDias.setText("Dia(s):");
        jPanelFundo.add(jLabelDias, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jComboBoxMes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBoxMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        jComboBoxMes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxMesItemStateChanged(evt);
            }
        });
        jComboBoxMes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxMesMouseClicked(evt);
            }
        });
        jComboBoxMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMesActionPerformed(evt);
            }
        });
        jPanelFundo.add(jComboBoxMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 100, 25));

        jButtonApagaMes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonApagaMes.setText("<--");
        jButtonApagaMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApagaMesActionPerformed(evt);
            }
        });
        jPanelFundo.add(jButtonApagaMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 50, 25));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Mês(es):");
        jPanelFundo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, -1, 20));

        jComboBoxDia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBoxDia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxDiaMouseClicked(evt);
            }
        });
        jComboBoxDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDiaActionPerformed(evt);
            }
        });
        jPanelFundo.add(jComboBoxDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 100, 25));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Dia(s) da Semana:");
        jPanelFundo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 270, -1, 20));

        jComboBoxDiaSemana.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBoxDiaSemana.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Domingo", "Segunda", "Terça", "Quarta", "Quinta", "Sexta", "Sábado" }));
        jComboBoxDiaSemana.setEnabled(false);
        jComboBoxDiaSemana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDiaSemanaActionPerformed(evt);
            }
        });
        jPanelFundo.add(jComboBoxDiaSemana, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 290, 100, 25));

        jButtonApagaDiaSemana.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonApagaDiaSemana.setText("<--");
        jButtonApagaDiaSemana.setEnabled(false);
        jButtonApagaDiaSemana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApagaDiaSemanaActionPerformed(evt);
            }
        });
        jPanelFundo.add(jButtonApagaDiaSemana, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 320, 50, 25));

        jLabelDiasUtil.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelDiasUtil.setForeground(new java.awt.Color(240, 240, 240));
        jLabelDiasUtil.setText("Dia(s) Útil(eis):");
        jPanelFundo.add(jLabelDiasUtil, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 270, -1, -1));

        jComboBoxDiaUtil.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBoxDiaUtil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1°", "2°", "3°", "4°", "5°", "6°", "7°", "8°", "9°", "10°", "11°", "12°", "13°", "14°", "15°", "16°", "17°", "18°", "19°", "20°", "21°", "22°", "23°" }));
        jComboBoxDiaUtil.setEnabled(false);
        jComboBoxDiaUtil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDiaUtilActionPerformed(evt);
            }
        });
        jPanelFundo.add(jComboBoxDiaUtil, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 290, 100, 25));

        jButtonApagaDiaUtil.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonApagaDiaUtil.setText("<--");
        jButtonApagaDiaUtil.setEnabled(false);
        jButtonApagaDiaUtil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApagaDiaUtilActionPerformed(evt);
            }
        });
        jPanelFundo.add(jButtonApagaDiaUtil, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 320, 50, 25));

        jCheckBoxReagendavel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBoxReagendavel.setForeground(new java.awt.Color(240, 240, 240));
        jCheckBoxReagendavel.setText("Reagendável");
        jCheckBoxReagendavel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxReagendavelActionPerformed(evt);
            }
        });
        jPanelFundo.add(jCheckBoxReagendavel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 120, -1));

        jCheckBoxPrioritario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBoxPrioritario.setForeground(new java.awt.Color(240, 240, 240));
        jCheckBoxPrioritario.setText("Prioritário");
        jPanelFundo.add(jCheckBoxPrioritario, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 120, -1));

        jCheckBoxHorarioFixo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBoxHorarioFixo.setForeground(new java.awt.Color(240, 240, 240));
        jCheckBoxHorarioFixo.setText("Horário Fixo");
        jPanelFundo.add(jCheckBoxHorarioFixo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 120, -1));

        jListDiaSemana.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jListDiaSemana.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(jListDiaSemana);

        jPanelFundo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 290, 100, 190));

        jListMes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jListMes.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(jListMes);

        jPanelFundo.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 100, 190));

        jListHorario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jListHorario.setModel(new DefaultListModel());
        jScrollPane3.setViewportView(jListHorario);

        jPanelFundo.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 290, 100, 190));

        jListDiaUtil.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jListDiaUtil.setModel(new DefaultListModel());
        jScrollPane4.setViewportView(jListDiaUtil);

        jPanelFundo.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 290, 100, 190));

        jListDia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jListDia.setModel(new DefaultListModel());
        jScrollPane5.setViewportView(jListDia);

        jPanelFundo.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 100, 190));

        jButtonApagaDia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonApagaDia.setText("<--");
        jButtonApagaDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApagaDiaActionPerformed(evt);
            }
        });
        jPanelFundo.add(jButtonApagaDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 50, 25));

        jComboBoxHora.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBoxHora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "7h", "8h", "9h", "10h", "11h", "12h", "13h", "14h", "15h", "16h", "17h" }));
        jComboBoxHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxHoraActionPerformed(evt);
            }
        });
        jPanelFundo.add(jComboBoxHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 290, 100, 25));

        jLabelAno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelAno.setForeground(new java.awt.Color(240, 240, 240));
        jLabelAno.setText("Ano(s)");
        jPanelFundo.add(jLabelAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, -1, -1));

        jListAno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jListAno.setModel(new DefaultListModel());
        jScrollPane6.setViewportView(jListAno);

        jPanelFundo.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, 100, 190));

        jComboBoxAno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBoxAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAnoActionPerformed(evt);
            }
        });
        jPanelFundo.add(jComboBoxAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, 100, 25));

        jButtonApagaAno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonApagaAno.setText("<--");
        jButtonApagaAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApagaAnoActionPerformed(evt);
            }
        });
        jPanelFundo.add(jButtonApagaAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, 50, 25));

        jButtonPeriodoInterrogacao.setText("?");
        jButtonPeriodoInterrogacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPeriodoInterrogacaoActionPerformed(evt);
            }
        });
        jPanelFundo.add(jButtonPeriodoInterrogacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 40, 20));

        jButtonPrioritarioInterrogacao.setText("?");
        jButtonPrioritarioInterrogacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrioritarioInterrogacaoActionPerformed(evt);
            }
        });
        jPanelFundo.add(jButtonPrioritarioInterrogacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, -1, 20));

        jButtonReagendavelInterrogacao.setText("?");
        jButtonReagendavelInterrogacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReagendavelInterrogacaoActionPerformed(evt);
            }
        });
        jPanelFundo.add(jButtonReagendavelInterrogacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, -1, 20));

        jButtonHorarioFixoInterrogacao.setText("?");
        jButtonHorarioFixoInterrogacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHorarioFixoInterrogacaoActionPerformed(evt);
            }
        });
        jPanelFundo.add(jButtonHorarioFixoInterrogacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, -1, 20));

        jPanelPrincipal.add(jPanelFundo, java.awt.BorderLayout.CENTER);

        jPanelTopo.setBackground(new java.awt.Color(0, 51, 65));
        jPanelTopo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 10, 0, new java.awt.Color(151, 154, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Vincular Rotina");
        jPanelTopo.add(jLabel1);

        jPanelPrincipal.add(jPanelTopo, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanelPrincipal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVincularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVincularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVincularActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        controller.cancelar();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jComboBoxPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPeriodoActionPerformed
        
        ((DefaultListModel)jListDia.getModel()).removeAllElements();
        ((DefaultListModel)jListMes.getModel()).removeAllElements();
        ((DefaultListModel)jListAno.getModel()).removeAllElements();
        ((DefaultListModel)jListDiaUtil.getModel()).removeAllElements();
        ((DefaultListModel)jListDiaSemana.getModel()).removeAllElements();
        ((DefaultListModel)jListHorario.getModel()).removeAllElements();
        switch (jComboBoxPeriodo.getSelectedIndex()){
            case 0: //Data Única
                jComboBoxDia.setEnabled(true);
                jButtonApagaDia.setEnabled(true);
                
                jComboBoxMes.setEnabled(true);
                jButtonApagaMes.setEnabled(true);
                            
                jComboBoxAno.setEnabled(true);
                jButtonApagaAno.setEnabled(true);
                             
                jComboBoxDiaSemana.setEnabled(false);
                jButtonApagaDiaSemana.setEnabled(false);
                     
                jComboBoxDiaUtil.setEnabled(false);
                jButtonApagaDiaUtil.setEnabled(false);
                break;
                
            case 1: //Diário
                jComboBoxDia.setEnabled(false);
                jButtonApagaDia.setEnabled(false);
                
                jComboBoxMes.setEnabled(false);
                jButtonApagaMes.setEnabled(false);
                
                jComboBoxAno.setEnabled(false);
                jButtonApagaAno.setEnabled(false);
                
                jComboBoxDiaSemana.setEnabled(false);
                jButtonApagaDiaSemana.setEnabled(false);
                
                jComboBoxDiaUtil.setEnabled(false);
                jButtonApagaDiaUtil.setEnabled(false);
                break;
                
            case 2: //Semanal
                
                jComboBoxDia.setEnabled(false);
                jButtonApagaDia.setEnabled(false);
                
                jComboBoxMes.setEnabled(false);
                jButtonApagaMes.setEnabled(false);
                
                jComboBoxAno.setEnabled(false);
                jButtonApagaAno.setEnabled(false);
                
                jComboBoxDiaSemana.setEnabled(true);
                jButtonApagaDiaSemana.setEnabled(true);
                
                jComboBoxDiaUtil.setEnabled(false);
                jButtonApagaDiaUtil.setEnabled(false);
                break;
             
             case 3: //Dia Útil/Mês
                
                jComboBoxDia.setEnabled(false);
                jButtonApagaDia.setEnabled(false);
                 
                jComboBoxMes.setEnabled(false);
                jButtonApagaMes.setEnabled(false);
                
                jComboBoxAno.setEnabled(false);
                jButtonApagaAno.setEnabled(false);
                
                jComboBoxDiaSemana.setEnabled(false);
                jButtonApagaDiaSemana.setEnabled(false);
                
                jComboBoxDiaUtil.setEnabled(true);
                jButtonApagaDiaUtil.setEnabled(true);
                break;
                
            case 4: //Dia/Mês
                
                jComboBoxDia.setEnabled(true);
                jButtonApagaDia.setEnabled(true);
                
                jComboBoxMes.setEnabled(false);
                jButtonApagaMes.setEnabled(false);
                
                jComboBoxAno.setEnabled(false);
                jButtonApagaAno.setEnabled(false);
                
                jComboBoxDiaSemana.setEnabled(false);
                jButtonApagaDiaSemana.setEnabled(false);
                
                jComboBoxDiaUtil.setEnabled(false);
                jButtonApagaDiaUtil.setEnabled(false);
                break;
            case 5: // Datas/Ano
                jComboBoxDia.setEnabled(true);
                jButtonApagaDia.setEnabled(true);
                
                jComboBoxMes.setEnabled(true);
                jButtonApagaMes.setEnabled(true);
                
                jComboBoxAno.setEnabled(false);
                jButtonApagaAno.setEnabled(false);
                
                jComboBoxDiaSemana.setEnabled(false);
                jButtonApagaDiaSemana.setEnabled(false);
                
                jComboBoxDiaUtil.setEnabled(false);
                jButtonApagaDiaUtil.setEnabled(false);
                
                break;
             case 6: //Anual
                
                jComboBoxDia.setEnabled(true);
                jButtonApagaDia.setEnabled(true);
                 
                jComboBoxMes.setEnabled(true);
                jButtonApagaMes.setEnabled(true);
                
                jComboBoxAno.setEnabled(false);
                jButtonApagaAno.setEnabled(false);
                
                jComboBoxDiaSemana.setEnabled(false);
                jButtonApagaDiaSemana.setEnabled(false);
                
                jComboBoxDiaUtil.setEnabled(false);
                jButtonApagaDiaUtil.setEnabled(false);
                break;
                
        }
    }//GEN-LAST:event_jComboBoxPeriodoActionPerformed

    private void jComboBoxMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMesActionPerformed
        
        preencherDia();
        
        DefaultListModel listModel = (DefaultListModel)jListMes.getModel();
        Object selectedItem = jComboBoxMes.getSelectedItem();
        
        if(jComboBoxPeriodo.getSelectedIndex() == 0 || jComboBoxPeriodo.getSelectedIndex() == 6){
            listModel.clear();
            listModel.addElement(selectedItem);
        } else 
        if(!listModel.contains(selectedItem)){
            listModel.addElement(selectedItem);
        } else JOptionPane.showMessageDialog(this,(String)selectedItem+" já esta na ista", "Lista de Meses", 1);
    }//GEN-LAST:event_jComboBoxMesActionPerformed

    private void jButtonApagaMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApagaMesActionPerformed
        ((DefaultListModel)jListMes.getModel()).removeElementAt(jListMes.getSelectedIndex());
    }//GEN-LAST:event_jButtonApagaMesActionPerformed

    private void jComboBoxDiaSemanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDiaSemanaActionPerformed
        DefaultListModel listModel = (DefaultListModel)jListDiaSemana.getModel();
        Object selectedItem = jComboBoxDiaSemana.getSelectedItem();
        if(!listModel.contains(selectedItem)){
            listModel.addElement(selectedItem);
        } else JOptionPane.showMessageDialog(this,(String)selectedItem+" já está na lista", "Lista de Semanas", 1);
    }//GEN-LAST:event_jComboBoxDiaSemanaActionPerformed

    private void jButtonApagaDiaSemanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApagaDiaSemanaActionPerformed
        ((DefaultListModel)jListDiaSemana.getModel()).remove(jListDiaSemana.getSelectedIndex());
    }//GEN-LAST:event_jButtonApagaDiaSemanaActionPerformed

    private void jComboBoxDiaUtilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDiaUtilActionPerformed
        DefaultListModel listModel = (DefaultListModel)jListDiaUtil.getModel();
        Object selectedItem = jComboBoxDiaUtil.getSelectedItem();
        if(!listModel.contains(selectedItem)){
            listModel.addElement(selectedItem);
        } else JOptionPane.showMessageDialog(this, (String)selectedItem+" dia útil já está na lista", "Dias úteis", 1);
        String opcao = "";
        
        if(selectedItem.equals("23°") || selectedItem.equals("22°") || selectedItem.equals("21°")){
            
            if(selectedItem.equals("23°")){
                opcao = "último";
            } else if (selectedItem.equals("22°")) {
                opcao = "penúltimo";
            } else if (selectedItem.equals("21°")) {
                opcao = "antepenúltimo";
            }
            JOptionPane.showMessageDialog(this, "Alguns meses não possuem o "+selectedItem+" dia útil, deseja marcar como "+opcao
                    +" dia útil do mês?", "Dias úteis",1);        
        }
    }//GEN-LAST:event_jComboBoxDiaUtilActionPerformed

    private void jButtonApagaDiaUtilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApagaDiaUtilActionPerformed
        int index = jListDiaUtil.getSelectedIndex();
        if(!(index < 0)){
          ((DefaultListModel)jListDiaUtil.getModel()).removeElementAt(index);  
        }
    }//GEN-LAST:event_jButtonApagaDiaUtilActionPerformed

    private void jComboBoxDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDiaActionPerformed
        
        if(jComboBoxDia.getActionCommand().equals("selecianaDia")){
            DefaultListModel listModel = (DefaultListModel)jListDia.getModel();
            Object selectedItem = jComboBoxDia.getSelectedItem();
        
            if(jComboBoxPeriodo.getSelectedIndex() == 0 || jComboBoxPeriodo.getSelectedIndex() == 5 || jComboBoxPeriodo.getSelectedIndex() == 6){
                listModel.clear();
                listModel.addElement(selectedItem);
            } 
            else
        
            if(!listModel.contains(selectedItem)){
                listModel.addElement(selectedItem);
            } else JOptionPane.showMessageDialog(this,(Integer)selectedItem+" dia já está na lista", "Dias do mês", 1);  
        }
        
    }//GEN-LAST:event_jComboBoxDiaActionPerformed

    private void jButtonApagaDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApagaDiaActionPerformed
        int index = jListDia.getSelectedIndex();
        if(!(index < 0)){
            ((DefaultListModel)jListDia.getModel()).removeElementAt(index);
        }
    }//GEN-LAST:event_jButtonApagaDiaActionPerformed

    private void jComboBoxHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxHoraActionPerformed
        DefaultListModel listModel = (DefaultListModel) jListHorario.getModel();
        Object selectedItem = jComboBoxHora.getSelectedItem();
        if(!listModel.contains(selectedItem)){
            listModel.addElement(selectedItem);
        } else JOptionPane.showMessageDialog(this, (String)selectedItem+" já está na lista", "Horário", 1);
    }//GEN-LAST:event_jComboBoxHoraActionPerformed

    private void jButtonApagaHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApagaHoraActionPerformed
        int index = jListHorario.getSelectedIndex();
        if(!(index < 0)){
            ((DefaultListModel)jListHorario.getModel()).removeElementAt(index);
        }
    }//GEN-LAST:event_jButtonApagaHoraActionPerformed

    private void jComboBoxAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAnoActionPerformed
        jComboBoxDia.setActionCommand("selecionaAno");
        ((DefaultListModel)jListAno.getModel()).removeAllElements();
        ((DefaultListModel)jListAno.getModel()).addElement(jComboBoxAno.getSelectedItem());
    }//GEN-LAST:event_jComboBoxAnoActionPerformed

    private void jButtonApagaAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApagaAnoActionPerformed
        ((DefaultListModel)jListAno.getModel()).removeElement(jListAno.getSelectedValue());
    }//GEN-LAST:event_jButtonApagaAnoActionPerformed

    private void jComboBoxMesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxMesMouseClicked
       
    }//GEN-LAST:event_jComboBoxMesMouseClicked

    private void jComboBoxMesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxMesItemStateChanged
        
    }//GEN-LAST:event_jComboBoxMesItemStateChanged

    private void jComboBoxDiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxDiaMouseClicked
        jComboBoxDia.setActionCommand("selecianaDia");
    }//GEN-LAST:event_jComboBoxDiaMouseClicked

    private void jButtonPeriodoInterrogacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPeriodoInterrogacaoActionPerformed
        String periodo = (String) jComboBoxPeriodo.getSelectedItem();
        String mensagem = "";
        switch (periodo){
            case "Data Única":
                mensagem =
                      "- Data fixa, que não se repete, como por exemplo uma reunião (dia, mês e ano único).\n"
                    + "- As opções Dia(s), Mês(es), Ano(s) e Horários vão estar ativadas.";
                break;
            case "Diário":
                mensagem = 
                          "- Rotina que se repete todos os dias.\n"
                        + "- Apenas a opção Horários vai estar ativa.";
                break;
            case "Semanal":
                mensagem = 
                          "- Rotina que se repete em um ou mais dia da semana, de acordo com as escolhas.\n"
                        + "- Apenas as opções Dia(s) da Semana e Horários vão estar ativas.";
                break;
            case "Dia Útil/Mês":
                mensagem =
                          "- Rotina que ocorra em determinados dias úteis do mês.\n"
                        + "- Por exemplo; Caso escolha o 1° e 10° dia útil, significa\n"
                        + " que a rotina vai ser agendada no primeiro e décimo dia útil\n"
                        + " de todos os meses\n"
                        + "- As opções Dia(s) Útil(eis) e Horários vão estar ativas";
                break;
            case "Dia/Mês":
                mensagem =
                          "- Rotina que ocorre em determinados dias do mês.\n"
                        + "- Por exemplo; Caso escolha o dia 1 e 10, significa que \n"
                        + "a rotina vai ser agendada todo dia 1 e 10 de todos os meses.\n"
                        + "- As opções Dia(s) e Horário vão estar ativas.";
                break;
            case "Datas/Ano":
                mensagem = 
                          "- Rotina que ocorre em um determinado dia e em meses selecionados.\n"
                        + "- Por exemplo; Caso escolha o dia 10 e os meses de Janeiro e Fevereiro\n"
                        + "significa que a rotina vai ser agendada todo dia 10 do mês de Janeiro e Fevereiro.\n"
                        + "- As opções Dia(s) (Apenas uma escolha) e Mês(ses) vão estar ativas.";
                break;
            case "Anual":
                mensagem = 
                          "- Rotina que ocorre uma vez por ano.\n"
                        + "- É necessário escolher o dia e o mês.\n"
                        + "- Opções Dia(s) e Mês(ses) ativas.";
                break;
                        
            
        }
        JOptionPane.showMessageDialog(this, mensagem, "Período: "+periodo, 3);
    }//GEN-LAST:event_jButtonPeriodoInterrogacaoActionPerformed

    private void jButtonPrioritarioInterrogacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrioritarioInterrogacaoActionPerformed
        JOptionPane.showMessageDialog(this, "- Rotina agendada com prioridade."
                + "\n- Marcar essa opção impacta no momento de resolver conflitos de Rotinas, ou seja, duas\n"
                + "rotinas que foram agendadas no mesmo horário, a marcada com prioridade vai ter preferência.",
                "Agendamento Prioritário", 3);
    }//GEN-LAST:event_jButtonPrioritarioInterrogacaoActionPerformed

    private void jButtonReagendavelInterrogacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReagendavelInterrogacaoActionPerformed
        JOptionPane.showMessageDialog(this, "- Rotina pode ser reagendada."
                + "\n- Marcar essa opção impacta que a rotina pode ter sua data e horário alterado posteriormente.",
                "Reagendável", 3);
    }//GEN-LAST:event_jButtonReagendavelInterrogacaoActionPerformed

    private void jButtonHorarioFixoInterrogacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHorarioFixoInterrogacaoActionPerformed
        JOptionPane.showMessageDialog(this, "- Rotina com horário fixo."
                + "\n- Marcar essa opção impacta que a rotina possui horários que não pode ser mudado e se torna\n"
                + "obrigatório a escolhe de um horário (Campo Horário se torna obrigatório).",
                "Horário Fixo", 3);
    }//GEN-LAST:event_jButtonHorarioFixoInterrogacaoActionPerformed

    private void jComboBoxRotinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxRotinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxRotinaActionPerformed

    private void jCheckBoxReagendavelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxReagendavelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxReagendavelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VincularRotinaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VincularRotinaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VincularRotinaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VincularRotinaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VincularRotinaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonApagaAno;
    private javax.swing.JButton jButtonApagaDia;
    private javax.swing.JButton jButtonApagaDiaSemana;
    private javax.swing.JButton jButtonApagaDiaUtil;
    private javax.swing.JButton jButtonApagaHora;
    private javax.swing.JButton jButtonApagaMes;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonHorarioFixoInterrogacao;
    private javax.swing.JButton jButtonPeriodoInterrogacao;
    private javax.swing.JButton jButtonPrioritarioInterrogacao;
    private javax.swing.JButton jButtonReagendavelInterrogacao;
    private javax.swing.JButton jButtonVincular;
    private javax.swing.JCheckBox jCheckBoxHorarioFixo;
    private javax.swing.JCheckBox jCheckBoxPrioritario;
    private javax.swing.JCheckBox jCheckBoxReagendavel;
    private javax.swing.JComboBox<Integer> jComboBoxAno;
    private javax.swing.JComboBox<Integer> jComboBoxDia;
    private javax.swing.JComboBox<String> jComboBoxDiaSemana;
    private javax.swing.JComboBox<String> jComboBoxDiaUtil;
    private javax.swing.JComboBox<String> jComboBoxFuncionario;
    private javax.swing.JComboBox<String> jComboBoxHora;
    private javax.swing.JComboBox<String> jComboBoxMes;
    private javax.swing.JComboBox<String> jComboBoxPeriodo;
    private javax.swing.JComboBox<String> jComboBoxRotina;
    private javax.swing.JComboBox<String> jComboBoxUnidade;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelAno;
    private javax.swing.JLabel jLabelDias;
    private javax.swing.JLabel jLabelDiasUtil;
    private javax.swing.JLabel jLabelFuncionario;
    private javax.swing.JLabel jLabelHora;
    private javax.swing.JLabel jLabelObservacao;
    private javax.swing.JLabel jLabelPeriodo;
    private javax.swing.JLabel jLabelRotina;
    private javax.swing.JLabel jLabelUnidade;
    private javax.swing.JList<String> jListAno;
    private javax.swing.JList<String> jListDia;
    private javax.swing.JList<String> jListDiaSemana;
    private javax.swing.JList<String> jListDiaUtil;
    private javax.swing.JList<String> jListHorario;
    private javax.swing.JList<String> jListMes;
    private javax.swing.JPanel jPanelFundo;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JPanel jPanelTopo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPaneObeservacao;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextAreaObservacao;
    // End of variables declaration//GEN-END:variables

    public void preencherAno() {
        Calendar dataHoje = Calendar.getInstance();
        int ano = dataHoje.get(Calendar.YEAR);
        for(int i = 0; i < 10; i++){
            jComboBoxAno.addItem(ano+i);
        }
    }
    
    public void preencherDia(){
        
        int mes;
        if(getjComboBoxMes().isEnabled()){
            mes = getjComboBoxMes().getSelectedIndex(); 
        } else mes = 0;
        
        int ano = Calendar.getInstance().get(Calendar.YEAR);
        int nDias = Calendario.nDias(mes+1, ano);
       
        jComboBoxDia.setActionCommand("selecionaMes");
        jComboBoxDia.removeAllItems();
        for(int i = 1; i<= nDias; i++){
            jComboBoxDia.addItem(i);
        }
    }
    
    public JComboBox<Integer> getjComboBoxDia() {
        return jComboBoxDia;
    }

    public JComboBox<String> getjComboBoxDiaSemana() {
        return jComboBoxDiaSemana;
    }

    public JComboBox<String> getjComboBoxDiaUtil() {
        return jComboBoxDiaUtil;
    }

    public JComboBox<String> getjComboBoxFuncionario() {
        return jComboBoxFuncionario;
    }

    public JComboBox<String> getjComboBoxHora() {
        return jComboBoxHora;
    }

    public JComboBox<String> getjComboBoxMes() {
        return jComboBoxMes;
    }

    public JComboBox<String> getjComboBoxPeriodo() {
        return jComboBoxPeriodo;
    }

    public JComboBox<String> getjComboBoxRotina() {
        return jComboBoxRotina;
    }

    public JComboBox<String> getjComboBoxUnidade() {
        return jComboBoxUnidade;
    }

    public JComboBox<Integer> getjComboBoxAno() {
        return jComboBoxAno;
    }
 
    
}
